package undertone.com.logging.util;

public enum MonitorMetric {

  GLOBAL_ERROR,
  INVALID_DATA_FORMAT,

  RECEIVED_IMPRESSIONS,
  FLUENTD_SEND_IMPRESSION,

  FLUENTD_SEND_FAILURE,
  FLUENTD_SEND_DURATION,
}
